---
title: "Lesson 2: Spatial Weights and Applications"
date: "13 Nov, 2023"
date-modified: "last-modified"
format: html
---

## Overview

In this lesson, you will learn a collection of geospatial statistical methods specially designed for measuring global and local spatial association.

These spatial statistics are well suited for:

-   detecting clusters or outliers;
-   identifying hot spot or cold spot areas;
-   assessing the assumptions of stationarity; and
-   identifying distances beyond which no discernible association obtains.

## Content

-   Concepts of Spatial Proximity and Spatial Weights
    -   Tobler's First law of Geography
    -   Contiguity-Based Spatial Weights: Rook's & Queen's
    -   Distance-Band Spatial Weights: fixed and adaptive
-   What is Spatial Autocorrelation
    -   Measures of Global Spatial Autocorrelation
    -   Measures of Global High/Low Clustering
-   Introducing Localised Geospatial Analysis
    -   Local Indicators of Spatial Association (LISA)
-   Cluster and Outlier Analysis
    -   Local Moran and Local Geary
    -   Moran scatterplot
    -   LISA Cluster Map
-   Hot Spot and Cold Spot Areas Analysis
    -   Getis and Ord's G-statistics
-   Emerging Hot Spot Analysis
    -   Space Time Cube
    -   Mann-Kendall test
    -   Emerging Hot Spot Analysis

## Lesson Slides

-   [Lesson 2: Spatial Weights and Applications](..\lesson\Lesson02\Lesson02-GLMSA.html).

## Hands-on Exercise

-   [Spatial Weights and Applications](https://r4gdsa.netlify.app/chap08)
-   [Global Measures of Spatial Autocorrelation](https://r4gdsa.netlify.app/chap09)
-   [Local Measures of Spatial Autocorrelation](https://r4gdsa.netlify.app/chap10)

## Self-reading Before Meet-up

To read before class:

-   Chapter 2. [Codifying the neighbourhood structure](https://www.insee.fr/en/statistiques/fichier/3635545/imet131-f-chapitre-2.pdf) of [Handbook of Spatial Analysis: Theory and Application with R](https://www.insee.fr/en/information/3635545).

-   Moran, P. A. P. (1950). ["Notes on Continuous Stochastic Phenomena"](https://www-jstor-org.libproxy.smu.edu.sg/stable/2332142?seq=1#metadata_info_tab_contents). Biometrika. 37 (1): 17--23.

-   Geary, R.C. (1954) ["The Contiguity Ratio and Statistical Mapping"](https://www-jstor-org.libproxy.smu.edu.sg/stable/2986645?sid=primo&origin=crossref&seq=1#metadata_info_tab_contents). *The Incorporated Statistician*, Vol. 5, No. 3, pp. 115-127.

-   Getis, A., & Ord, K. (1992). ["The Analysis of Spatial Association by Use of Distance Statistics"](https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1538-4632.1992.tb00261.x). *Geographical Analysis*, 24, 189--206.

-   Anselin, L. (1995). ["Local indicators of spatial association -- LISA"](https://onlinelibrary.wiley.com/doi/10.1111/j.1538-4632.1995.tb00338.x). *Geographical Analysis*, 27(4): 93-115.

-   Ord, J.K. and Getis, A. (2010) ["Local spatial autocorrelation statistics: Distributional issues and an application"](https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1538-4632.1995.tb00912.x). *Geographical Analysis*, 27(4): 286-306.

These six papers are classics of Global and Local Spatial Autocorrelation. Be warned: All classic papers assume that the readers are academic researchers.

- Sarah Gates (2017) ["Emerging Hot Spot Analysis: Finding Patterns over Space and Time"](https://www.azavea.com/blog/2017/08/15/emerging-hot-spot-spatial-statistics/)

## References

-   D. A. Griffith (2009) "Spatial autocorrelation".
-   Getis, A., 2010 "B.3 Spatial Autocorrelation" in Fischer, M.M., and Getis, A. 2010 Handbook of Applied Spatial Analysis: Software Tools, Methods and Applications, Springer.
-   Anselin, L. (1996) "The Moran scatterplot as an ESDA tool to assess local instability in spatial association"
-   Griffith, Daniel (2009) "Modeling spatial autocorrelation in spatial interaction data: empirical evidence from 2002 Germany journey-to-work flows". Journal of Geographical Systems, Vol.11(2), pp.117-140.
-   Celebioglu, F., and Dall'erba, S. (2010) "Spatial disparities across the regions of Turkey: An exploratory spatial data analysis". The Annals of Regional Science, 45:379--400.
-   Mack, Z.W.V. and Kam T.S. (2018) ["Is There Space for Violence?: A Data-driven Approach to the Exploration of Spatial-Temporal Dimensions of Conflict"](https://ink.library.smu.edu.sg/sis_research/4331/) *Proceedings of 2nd ACM SIGSPATIAL Workshop on Geospatial Humanities (ACM SIGSPATIAL'18)*. Seattle, Washington, USA, 10 pages.
-   TAN, Yong Ying and KAM, Tin Seong (2019). ["Exploring and Visualizing Household Electricity Consumption Patterns in Singapore: A Geospatial Analytics Approach"](https://ink.library.smu.edu.sg/sis_research/4376/), *Information in Contemporary Society: 14th International Conference*, iConference 2019, Washington, DC, USA, March 31--April 3, 2019, Proceedings. Pp 785-796.
-   Singh A., Pathak P.K., Chauhan R.K., and Pan, W. (2011) "Infant and Child Mortality in India in the Last Two Decades: A Geospatial Analysis". PLoS ONE 6(11), 1:19.

## All About R

-   [sfdep](https://sfdep.josiahparry.com/) package.
    -   [The Basics of sfdep](https://sfdep.josiahparry.com/articles/basics-of-sfdep)
    -   [Spacetime and Spacetime cubes](https://sfdep.josiahparry.com/articles/spacetime-s3)
    -   [Emerging Hot Spot Analysis](https://sfdep.josiahparry.com/articles/understanding-emerging-hotspots)
    -   [Conditional Permutations with sfdep](https://sfdep.josiahparry.com/articles/conditional-permutation)
